name: Pull request checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - run: npm ci

      # Run Lint check
      - run: npm run lint

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - run: npm ci

      # Run unit Tests
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          test-script: npm run test
          output: comment, report-markdown

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - run: npm ci

      # Make sure MFE builds as smoke test
      - run: npm run build
